import { Project, TranslationsObject } from '@/types/common'

export const getProjects = (
  translations: TranslationsObject,
  lang: string
): Project[] => [
  {
    id: 13,
    title: translations[lang].projects.asiamotors_app,
    description: translations[lang].projects.asiamotors_app__descr,
    image: '/img/project/asiamotots-project.jpg',
    liveLink: 'https://asiamotors.su/',
    codeLink: 'https://github.com/Father1993/AsiaMotors',
  },
  {
    id: 14,
    title: translations[lang].projects.magnitola_app,
    description: translations[lang].projects.magnitola_app__descr,
    image: '/img/project/magnitola.jpg',
    liveLink: 'https://magitola.netlify.app/',
    codeLink: 'https://github.com/Father1993/audioShop',
  },
  {
    id: 1,
    title: translations[lang].projects.react_web_app,
    description: translations[lang].projects.react_web_app_descr,
    image: '/img/project/tigai_preview.jpg',
    liveLink: 'https://tigay.ru/',
    codeLink: 'https://github.com/Father1993/Aleksey-Tigay-website',
  },
  {
    id: 15,
    title: translations[lang].projects.admin_panel,
    description: translations[lang].projects.admin_panel__descr,
    image: '/img/project/admin-panel.jpg',
    codeLink: 'https://github.com/Father1993/audioShop_admin',
  },
  {
    id: 16,
    title: translations[lang].projects.tg_as_bot,
    description: translations[lang].projects.tg_as_bot__descr,
    image: '/img/project/tg_bot.jpg',
    liveLink: 'https://t.me/asiamotors27_bot',
    codeLink: 'https://github.com/Father1993/tg_asiamotors_bot',
  },
  {
    id: 17,
    title: translations[lang].projects.calculator_as_app,
    description: translations[lang].projects.calculator_as_app__descr,
    image: '/img/project/calculator-as.jpg',
    liveLink: 'https://asiamotors.netlify.app/',
    codeLink: 'https://github.com/Father1993/Automobile-calculator',
  },
  {
    id: 7,
    title: translations[lang].projects.nextjs_sites,
    description: translations[lang].projects.nextjs_sites_descr,
    image: '/img/project/perevozka.jpg',
    liveLink: 'https://perevozka27.ru/',
    codeLink: 'https://xn--90anbgibdchfetk.xn--p1ai/',
  },
  {
    id: 18,
    title: translations[lang].projects.rukti_website,
    description: translations[lang].projects.rukti_website__descr,
    image: '/img/project/rukti.jpg',
    liveLink: 'https://rukti-khv.ru/',
    codeLink: 'https://github.com/Father1993/Nails-website',
  },
  {
    id: 2,
    title: translations[lang].projects.i_shop,
    description: translations[lang].projects.i_shop_descr,
    image: '/img/project/store_app.jpg',
    liveLink: 'https://main--somestorespinej.netlify.app/',
    codeLink: 'https://github.com/Father1993/Online-jewelry-store-via-API',
  },
  {
    id: 4,
    title: translations[lang].projects.book_lib,
    description: translations[lang].projects.book_lib_descr,
    image: '/img/project/lib_app.jpg',
    codeLink: 'https://github.com/Father1993/Books-Library-App',
  },
  {
    id: 5,
    title: translations[lang].projects.electrosystems,
    description: translations[lang].projects.electrosystems_descr,
    image: '/img/project/es-dv_preview.jpg',
    liveLink: 'https://es-dv.ru',
    codeLink: 'https://github.com/Father1993/es-dv',
  },
  {
    id: 3,
    title: translations[lang].projects.xinrosh,
    description: translations[lang].projects.xinrosh_descr,
    image: '/img/project/xinros_preview.jpeg',
  },
  {
    id: 6,
    title: translations[lang].projects.plumber,
    description: translations[lang].projects.plumber_descr,
    image: '/img/project/plumber_preview.jpg',
    liveLink: 'https://plumkhv.netlify.app/',
    codeLink: 'https://github.com/Father1993/Plumber-regional-site',
  },
  {
    id: 8,
    title: translations[lang].projects.students_app,
    description: translations[lang].projects.students_app_descr,
    image: '/img/project/students-form_preview.jpg',
    codeLink: 'https://github.com/Father1993/Vanila-JS-Forms-Filter-Render',
  },
  {
    id: 9,
    title: translations[lang].projects.react_app_old,
    description: translations[lang].projects.react_app_old_descr,
    image: '/img/project/react_app_preview.jpg',
    codeLink: 'https://github.com/Father1993/React_app_practice',
  },
  {
    id: 10,
    title: translations[lang].projects.docker_in_project,
    description: translations[lang].projects.docker_in_project_descr,
    image: '/img/project/time_app_nodejs_preview.jpg',
    codeLink: 'https://github.com/Father1993/Docker-full-practice',
  },
  {
    id: 11,
    title: translations[lang].projects.vanilla_js,
    description: translations[lang].projects.vanilla_js_descr,
    image: '/img/project/vanilla_js_preview.jpg',
    liveLink:
      'https://65c60a3cd060d29373d059d2--fascinating-quokka-0f8f87.netlify.app/',
    codeLink: 'https://github.com/Father1993/MemoryGameJS/tree/main',
  },
  {
    id: 12,
    title: translations[lang].projects.calculate_webapp,
    description: translations[lang].projects.calculate_webapp_descr,
    image: '/img/project/calc_preview.jpg',
    codeLink: 'https://github.com/Father1993/Foreign-car-buying-calculator',
  },
]

export default getProjects
