/* eslint-disable @next/next/no-img-element */

const Skills = () => (
  <section className='skills' id='skills'>
    <div className='skills__wrapper container scroll-animation-right'>
      <div className='row'>
        <h2 className='skills__title margin__text'>Skills</h2>
        <h3 className='skills__description'>
          Навыки, инструменты и технологии, в которых я разбираюсь:
        </h3>
        <div className='skills__block'>
          <ul className='skills__list'>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/js.webp'
                alt='JS_icon'
              />
              JavaScript
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/react.webp'
                alt='React_icon'
              />
              React
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/node.webp'
                alt='Node_icon'
              />
              Node.js
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/docker.webp'
                alt='Docker_icon'
              />
              Docker
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/html.webp'
                alt='HTML_icon'
              />
              HTML
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/css.webp'
                alt='CSS_icon'
              />
              CSS
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/php.webp'
                alt='PHP_icon'
              />
              PHP
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/python.webp'
                alt='Python_icon'
              />
              Python
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/redux.webp'
                alt='Redux_icon'
              />
              Redux
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/sql.webp'
                alt='SQL_icon'
              />
              SQL
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/bootstap.webp'
                alt='Bootstrap_icon'
              />
              Bootstrap
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/wordpress.webp'
                alt='WordPress_icon'
              />
              WordPress
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/git.webp'
                alt='Git_icon'
              />
              Git
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/npm.webp'
                alt='NPM_icon'
              />
              npm
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/bash.webp'
                alt='Bash_icon'
              />
              bash
            </li>
            <li>
              <img
                decoding='async'
                className='skills__icon'
                src='./img/tech/linux.webp'
                alt='Linux_icon'
              />
              Linux
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
)

export default Skills
